/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Dimension;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author rfid
 */
public class DemSoDongCuaDonHang extends javax.swing.JFrame {

    private JLabel lblFileName;
    private JButton btnChonFile, btnXuatFile, btnChonFolder;
    private File[] selectedFiles;
    private File selectedFolder;
    
    /**
     * Creates new form DemSoDongCuaDonHang
     */
    public DemSoDongCuaDonHang() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_ChonFile = new javax.swing.JButton();
        btn_XuatFile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_noi_dung = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Đếm Số Dòng ");

        btn_ChonFile.setText("Chọn File");
        btn_ChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonFileActionPerformed(evt);
            }
        });

        btn_XuatFile.setText("Xuất File");
        btn_XuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XuatFileActionPerformed(evt);
            }
        });

        jButton1.setText("Chọn Foder Ra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txa_noi_dung.setColumns(20);
        txa_noi_dung.setRows(5);
        jScrollPane1.setViewportView(txa_noi_dung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(468, 468, 468)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_XuatFile)
                            .addComponent(btn_ChonFile)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_ChonFile)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btn_XuatFile)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setPreferredSize(new Dimension(800,600));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFiles = fileChooser.getSelectedFiles();
            StringBuilder sb = new StringBuilder("Selected files:\n");
            for (File file : selectedFiles) {
                sb.append(file.getName()).append("\n");
            }
            sb.append("\nTotal files: ").append(selectedFiles.length);
            txa_noi_dung.setText(sb.toString());
        }
    }//GEN-LAST:event_btn_ChonFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser folderChooser = new JFileChooser();
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setPreferredSize(new Dimension(800,600));
        int result = folderChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFolder = folderChooser.getSelectedFile();
            JOptionPane.showMessageDialog(this, "Thư mục đã chọn: " + selectedFolder.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_XuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XuatFileActionPerformed
        // TODO add your handling code here:
        if (selectedFiles == null || selectedFolder == null) {
            JOptionPane.showMessageDialog(this, "Hãy chọn file và thư mục lưu trước khi xuất file!");
            return;
        }

        // Lấy tên của file đầu tiên và file cuối cùng trong danh sách
        String firstFileName = extractPoNumber(selectedFiles[0].getName());
        String lastFileName = extractPoNumber(selectedFiles[selectedFiles.length - 1].getName());

        // Tạo tên file output theo format mong muốn
        String outputFileName = firstFileName + "_" + lastFileName + ".csv";
        String outputFilePath = selectedFolder.getAbsolutePath() + File.separator + outputFileName;

        try (FileWriter writer = new FileWriter(outputFilePath)) {
            writer.append("File Name, PO Number, Line Count\n");
            for (File file : selectedFiles) {
                String fileName = file.getName();
                String poNumber = extractPoNumber(fileName);
                long lineCount = Files.lines(Paths.get(file.getAbsolutePath())).count();
                writer.append(fileName).append(", ").append(poNumber).append(", ").append(String.valueOf(lineCount)).append("\n");
            }
            JOptionPane.showMessageDialog(this, "File đã xuất thành công: " + outputFilePath);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xuất file: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_XuatFileActionPerformed

    private String extractPoNumber(String fileName) {
        // Giả sử PO là chuỗi số đầu tiên trong tên file
        String[] parts = fileName.split("_");
        return parts[0];
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemSoDongCuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemSoDongCuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemSoDongCuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemSoDongCuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemSoDongCuaDonHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChonFile;
    private javax.swing.JButton btn_XuatFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txa_noi_dung;
    // End of variables declaration//GEN-END:variables
}
