/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author rfid
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        setAppIcon();
    }

    private void setAppIcon() {
        String iconPath = "/Img/Logo_RFID_NAMVIET-01.jpg";
        java.net.URL iconURL = getClass().getResource(iconPath);

        if (iconURL != null) {
            try {
                ImageIcon icon = new ImageIcon(iconURL);
                this.setIconImage(icon.getImage());
            } catch (Exception e) {
                System.err.println("Lỗi khi đọc hình ảnh: " + e.getMessage());
            }
        } else {
            System.err.println("Không thể tìm thấy tài nguyên hình ảnh tại " + iconPath);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_PhanCongCongViec = new javax.swing.JButton();
        btn_ChuyenDoiEpc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_dem_sl_dong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_PhanCongCongViec.setText("Phân Công Công Việc");
        btn_PhanCongCongViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhanCongCongViecActionPerformed(evt);
            }
        });

        btn_ChuyenDoiEpc.setText("Chuyển Đổi Epc");
        btn_ChuyenDoiEpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChuyenDoiEpcActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ứng dụng phòng RFID");

        btn_dem_sl_dong.setText("Đếm Số Lượng Dòng Trong File");
        btn_dem_sl_dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dem_sl_dongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btn_PhanCongCongViec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ChuyenDoiEpc)
                        .addGap(18, 18, 18)
                        .addComponent(btn_dem_sl_dong)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_PhanCongCongViec)
                    .addComponent(btn_ChuyenDoiEpc)
                    .addComponent(btn_dem_sl_dong))
                .addContainerGap(319, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PhanCongCongViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhanCongCongViecActionPerformed
        // TODO add your handling code here:
        PhanCongCV phanCong = new PhanCongCV();
        phanCong.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        phanCong.setVisible(true);
    }//GEN-LAST:event_btn_PhanCongCongViecActionPerformed

    private void btn_ChuyenDoiEpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChuyenDoiEpcActionPerformed
        // TODO add your handling code here:
        GiaoDien giaodien = new GiaoDien();
        giaodien.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        giaodien.setVisible(true);
    }//GEN-LAST:event_btn_ChuyenDoiEpcActionPerformed

    private void btn_dem_sl_dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dem_sl_dongActionPerformed
        // TODO add your handling code here:
        DemSoDongCuaDonHang demsldh = new DemSoDongCuaDonHang();
        demsldh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        demsldh.setVisible(true);
    }//GEN-LAST:event_btn_dem_sl_dongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            // Set the Look and Feel to Nimbus
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChuyenDoiEpc;
    private javax.swing.JButton btn_PhanCongCongViec;
    private javax.swing.JButton btn_dem_sl_dong;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
